from tkinter import*
root=Tk()
root.title("Form")
l1=Label(root,text="Student form",font=("calibri",20),fg="Blue")
l1.pack()
l2=Label(root,text="Student Name",font=("Adiro",14),fg="green")
l2.place(x=10,y=50)
e1=Entry(root,bg="grey",fg="red",bd=2)
e1.place(x=150,y=50)
l3=Label(root,text="Student No",font=("Adiro",14),fg="green")
l3.place(x=10,y=100)
e2=Entry(root,bg="grey",fg="red",bd=2)
e2.place(x=150,y=100)
l4=Label(root,text="Email",fg="green",font=("Adiro",14))
l4.place(x=10,y=150)
e3=Entry(root,fg="red",bg="grey",bd=2)
e3.place(x=150,y=150)
l5=Label(root,text="Mark",fg="green",font=("Adiro",14))
l5.place(x=10,y=200)
e4=Entry(root,fg="red",bg="grey",bd=2)
e4.place(x=150,y=200)
def submit():
    print("your form is submitted")
btn=Button(root,text="Submit",fg="black",bg="yellow",font=("Adiro",14),command=submit)
btn.place(x=150,y=250)    
root.geometry("400x500")
root.mainloop()
